version: '3.8'

services:
  database:
    image: postgres:15
    container_name: movies_rental_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
  pgdata:
